onboarding = false

[theme]
name = "catppuccin"

[keys]
prefix = "ctrl+space"
previous_tab = "cmd+shift+left"
next_tab = "cmd+shift+right"
previous_workspace = "cmd+shift+up"
next_workspace = "cmd+shift+down"
new_tab = "cmd+shift+n"
close_tab = "cmd+shift+w"
rename_tab = "cmd+shift+r"

[ui]
agent_panel_scope = "all"
show_agent_labels_on_pane_borders = true
prompt_new_tab_name = false

[experimental]
kitty_graphics = true
pane_history = true
