root = true
if_missing = "error"
env = "exec"

[providers.bitwarden]
type = "bitwarden"

[secrets]
PATOUMATIC_SERVER_IP = { provider = "bitwarden", value = "dotfiles-repository/PATOUMATIC_SERVER_IP" }
PATOUMATIC_SERVER_USER = { provider = "bitwarden", value = "dotfiles-repository/PATOUMATIC_SERVER_USER" }
CROOZ_SERVER_IP = { provider = "bitwarden", value = "dotfiles-repository/CROOZ_SERVER_IP" }
CROOZ_SERVER_USER = { provider = "bitwarden", value = "dotfiles-repository/CROOZ_SERVER_USER" }
AZADE_SERVER_IP = { provider = "bitwarden", value = "dotfiles-repository/AZADE_SERVER_IP" }
AZADE_SERVER_USER = { provider = "bitwarden", value = "dotfiles-repository/AZADE_SERVER_USER" }
BADGER_SERVER_IP = { provider = "bitwarden", value = "dotfiles-repository/BADGER_SERVER_IP" }
BADGER_SERVER_USER = { provider = "bitwarden", value = "dotfiles-repository/BADGER_SERVER_USER" }
PATOUMATIC_RAILS_DEVELOPMENT_KEY = { provider = "bitwarden", value = "patoumatic-repository/RAILS_DEVELOPMENT_KEY" }
CROOZ_RAILS_DEVELOPMENT_KEY = { provider = "bitwarden", value = "crooz-repository/RAILS_DEVELOPMENT_KEY" }
