root = true
if_missing = "error"

[providers.bitwarden]
type = "bitwarden"

[secrets]
SSH_PATOUMATIC_IP = { provider = "bitwarden", value = "dotfiles/SSH_PATOUMATIC_IP" }
SSH_PATOUMATIC_USER = { provider = "bitwarden", value = "dotfiles/SSH_PATOUMATIC_USER" }
SSH_CROOZ_IP = { provider = "bitwarden", value = "dotfiles/SSH_CROOZ_IP" }
SSH_CROOZ_USER = { provider = "bitwarden", value = "dotfiles/SSH_CROOZ_USER" }
SSH_AZADE_IP = { provider = "bitwarden", value = "dotfiles/SSH_AZADE_IP" }
SSH_AZADE_USER = { provider = "bitwarden", value = "dotfiles/SSH_AZADE_USER" }
SSH_BADGER_IP = { provider = "bitwarden", value = "dotfiles/SSH_BADGER_IP" }
SSH_BADGER_USER = { provider = "bitwarden", value = "dotfiles/SSH_BADGER_USER" }
