ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"
plugins=(common-aliases git gitfast heroku history-substring-search last-working-dir osx vscode zsh-syntax-highlighting)

export HOMEBREW_NO_ANALYTICS=1

source "${ZSH}/oh-my-zsh.sh"
unalias rm

type -a rbenv > /dev/null && eval "$(rbenv init -)"

# type -a pyenv > /dev/null && eval "$(pyenv init -)" && eval "$(pyenv virtualenv-init -)"

# export PATH="./bin:./node_modules/.bin:${PATH}:/usr/local/sbin"

[[ -f "$HOME/.aliases" ]] && source "$HOME/.aliases"

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export BUNDLER_EDITOR=code
export EDITOR="code --wait"
