ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"
plugins=(common-aliases git gitfast heroku history-substring-search last-working-dir macos sublime vscode zsh-syntax-highlighting)

export HOMEBREW_NO_ANALYTICS=1

source "${ZSH}/oh-my-zsh.sh"
unalias rm

type -a rbenv > /dev/null && eval "$(rbenv init -)"

# type -a pyenv > /dev/null && eval "$(pyenv init -)" && eval "$(pyenv virtualenv-init -)"

# export PATH="./bin:./node_modules/.bin:${PATH}:/usr/local/sbin"

export PATH="./bin:${PATH}"

export PATH="/Applications/Sublime Text.app/Contents/SharedSupport/bin:$PATH"

[[ -f "$HOME/.aliases" ]] && source "$HOME/.aliases"

source ~/.zsh/completion/scalingo_complete.zsh

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export BUNDLER_EDITOR=code
export EDITOR="code --wait"

export CONSOLE_USER="François"

export AWS_PROFILE="kms-grants"

# https://stackoverflow.com/questions/43489303/how-can-i-delete-all-git-branches-which-have-been-squash-and-merge-via-github
sweep () {
  git checkout -q main && git for-each-ref refs/heads/ "--format=%(refname:short)" | while read branch; do mergeBase=$(git merge-base main $branch) && [[ $(git cherry main $(git commit-tree $(git rev-parse "$branch^{tree}") -p $mergeBase -m _)) == "-"* ]] && git branch -D $branch; done
}
