[tools]
age = "latest"
claude = "latest"
codex = "latest"
gh = "latest"
herdr = "latest"
node = "latest"
npm = "12"
"npm:agent-browser" = "latest"
"npm:@doist/outline-cli" = { version = "latest", allow_low_downloads = true }
pi = { version = "latest", minimum_release_age = "0" }
ruby = "latest"
stripe = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]
compile = false
