# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    # gaps_in = 0
    # gaps_out = 0
    # border_size = 0

    # Use master layout instead of dwindle
    # layout = master
}

# Laptop screen (eDP-1): tighter gaps, no gaps/border when only 1 visible tiled window
workspace = m[eDP-1], gapsin:2, gapsout:4
workspace = w[tv1]m[eDP-1], gapsout:0, border:false

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    # rounding = 8
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}
