schema_version = 3

[app_settings]
launch_at_login = true
check_for_updates = true
auto_install_updates = false
update_prompt_seen = true
show_in_menu_bar = false
auto_download_assets = true
thumbwheel_sensitivity = 14
appearance = "system"

[devices.1b034.bindings.GestureButton]
Left = "PreviousDesktop"
Right = "NextDesktop"
Click = "MissionControl"

[devices."receiver:aa1b0f44a71c6b5e:slot:2"]
gesture_owner = "Off"

[devices."receiver:aa1b0f44a71c6b5e:slot:2".identity]
display_name = "MX Master 3S"
codename = "MX Master 3S"
kind = "mouse"

[devices."receiver:aa1b0f44a71c6b5e:slot:2".identity.model_info]
entity_count = 3
unit_id = [
    0,
    0,
    0,
    0,
]
model_ids = [
    45108,
    0,
    0,
]
extended_model_id = 1

[devices."receiver:aa1b0f44a71c6b5e:slot:2".identity.model_info.transports]
usb = false
equad = false
btle = true
bluetooth = false

[devices."receiver:aa1b0f44a71c6b5e:slot:2".identity.capabilities]
buttons = true
pointer = true
lighting = false
scroll_inversion = true
hires_wheel = true

[devices."receiver:aa1b0f44a71c6b5e:slot:2".bindings]
Forward = "PreviousDesktop"
DpiToggle = "MissionControl"
GestureButton = "BrowserBack"

[devices."receiver:aa1b0f44a71c6b5e:slot:2".bindings.Back]
Up = "MissionControl"
Down = "ShowDesktop"
Left = "PrevTab"
Right = "NextTab"
Click = "NextDesktop"

[devices."receiver:aa1b0f44a71c6b5e:slot:2".smartshift]
mode = "free"
auto_disengage = 10
tunable_torque = 0
