ZSH=$HOME/.oh-my-zsh
ZSH_THEME=robbyrussell
plugins=(common-aliases git gitfast history-substring-search kamal last-working-dir macos vscode)
# Cloned by `setup:zsh`. Highlighting has to stay last.
for _p in zsh-autosuggestions zsh-syntax-highlighting; do
  [[ -d "${ZSH_CUSTOM:-$ZSH/custom}/plugins/$_p" ]] && plugins+=($_p)
done
unset _p

export HOMEBREW_NO_ANALYTICS=1

[[ -f "${ZSH}/oh-my-zsh.sh" ]] && source "${ZSH}/oh-my-zsh.sh"
[[ -f /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]] && source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
(( ${+aliases[rm]} )) && unalias rm

type -a mise > /dev/null && eval "$(mise activate zsh)"

export PATH="$HOME/.local/bin:${PATH}"
# export PATH="./bin:$HOME/.local/bin:${PATH}"

[[ -f "$HOME/.aliases" ]] && source "$HOME/.aliases"

export LANG=en_US.UTF-8

command -v code > /dev/null && export EDITOR="code --wait" || export EDITOR=vim
export BUNDLER_EDITOR="$EDITOR"

export CONSOLE_USER="François Catuhe"

# ---------------------------------------------------------------------------

# Ridecell
export AWS_PROFILE=ridecell
export AWS_REGION=us-west-2
# export CLAUDE_CODE_USE_BEDROCK=1
