[tools]
bun = "latest"
claude = "latest"
codex = "latest"
fnox = "latest"
gh = "latest"
node = "latest"
npm = "latest"
"npm:@doist/outline-cli" = { version = "latest", allow_low_downloads = true }
"npm:agent-browser" = "latest"
pi = { version = "latest", minimum_release_age = "0" }
ruby = "latest"
stripe = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]
compile = false
