[tools]
"aqua:modem-dev/hunk" = "latest"
bun = "latest"
fnox = "latest"
gh = "latest"
"github:basecamp/hey-cli" = "latest"
node = "latest"
npm = "latest"
"npm:@doist/outline-cli" = { version = "latest", allow_low_downloads = true }
"npm:@kitlangton/ghui" = "latest"
"npm:agent-browser" = "latest"
pi = { version = "latest", minimum_release_age = "0" }
ruby = "latest"
stripe = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]
compile = false
