[tools]
age = "latest"
codex = "latest"
gh = "latest"
node = "latest"
pi = { version = "latest", minimum_release_age = "0" }
ruby = "latest"
stripe = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]
compile = false
